### ISSUE TITLE
[ENHANCEMENT] Change receive pop up dialog

### ISSUE THREAD

**Issue by gungdesurya** [zoobc/zoobc-wallet-web#529]
When clicking Receive menu on sidebar, check console, there is any error message

**Comment by zaenury** [comment]
Cannot match any routes. url segment angular. This happen when clicking receive menu on sidebar

![image](https://user-images.githubusercontent.com/42806183/109591392-6195c880-7b48-11eb-9c16-8ad510665e95.png)
